backend:
  name: github
  repo: atchouna-blip/jsb3-site
  branch: main
  open_authoring: true

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "site"
    label: "Contenus du site"
    files:
      - file: "content/site.json"
        label: "Paramètres & Sections"
        name: "site"
        fields:
          - { label: "Nom de l’événement", name: "eventName", widget: "string" }
          - { label: "Thème", name: "theme", widget: "string" }
          - { label: "Dates (affichage)", name: "datesDisplay", widget: "string" }
          - { label: "Lieu (affichage)", name: "venueDisplay", widget: "string" }
          # (Ajoute tes autres champs à la suite...)
  - name: "speakers"
    label: "Conférenciers invités"
    files:
      - file: "content/speakers.json"
        label: "Liste des conférenciers"
        name: "speakers"
        fields:
          - { label: "Titre de section", name: "title", widget: "string" }
          - label: "Conférenciers"
            name: "items"
            widget: "list"
            fields:
              - {label: "Nom", name: "name", widget: "string"}
              - {label: "Rôle/fonction", name: "role", widget: "string"}
              - {label: "Institution", name: "institution", widget: "string"}
              - {label: "Photo", name: "photo", widget: "image"}
              - {label: "Bio", name: "bio", widget: "text"}
  - name: "news"
    label: "Actualités"
    files:
      - file: "content/news.json"
        label: "Articles"
        name: "news"
        fields:
          - { label: "Titre de section", name: "title", widget: "string" }
          - label: "Articles"
            name: "items"
            widget: "list"
            fields:
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
              - {label: "Image", name: "cover", widget: "image"}
              - {label: "Chapo", name: "excerpt", widget: "text"}
              - {label: "Corps", name: "body", widget: "text"}
  - name: "program"
    label: "Programme"
    files:
      - file: "content/program.json"
        label: "Planning/Sessions"
        name: "program"
        fields:
          - {label: "Titre de page", name: "title", widget: "string"}
          - label: "Tracks"
            name: "tracks"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "string"}
              - {label: "Libellé", name: "label", widget: "string"}
              - {label: "Couleur", name: "color", widget: "string"}
          - label: "Journées"
            name: "days"
            widget: "list"
            fields:
              - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
              - {label: "Libellé", name: "label", widget: "string"}
              - label: "Créneaux"
                name: "slots"
                widget: "list"
                fields:
                  - {label: "Heure", name: "time", widget: "string"}
                  - {label: "Type", name: "type", widget: "string"}
                  - {label: "Titre", name: "title", widget: "string"}
                  - label: "Intervenants"
                    name: "speakers"
                    widget: "list"
                    field: {label: "Nom", name: "item", widget: "string"}
  - name: "partners"
    label: "Partenaires"
    files:
      - file: "content/partners.json"
        label: "Partenaires & sponsors"
        name: "partners"
        fields:
          - {label: "Titre", name: "title", widget: "string"}
          - label: "Tiers"
            name: "tiers"
            widget: "list"
            fields:
              - { label: "Nom du niveau", name: "name", widget: "string" }
              - label: "Partenaires"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Nom", name: "name", widget: "string" }
                  - { label: "Logo", name: "logo", widget: "image" }
                  - { label: "URL", name: "url", widget: "string" }

media_library:
  name: uploadcare
  config:
    publicKey: demopublickey
